name: desi_wanderer

services:
  keycloak_db:
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak_db
    image: postgres:18.4
    restart: always
    ports:
      - "${KEYCLOAK_DB_PORT}:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=1
      -c max_replication_slots=1

  kafka:
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    image: apache/kafka:4.2.0
    restart: always
    ports:
      - "${KAFKA_PORT}:9094"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - kafka_secrets:/etc/kafka/secrets
      - kafka_shared_config:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  keycloak:
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak
    image: keycloak/keycloak:26.6.1
    restart: always
    depends_on:
      - keycloak_db
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./config/keycloak/realm/desi-wanderer.json:/opt/keycloak/data/import/desi-wanderer.json:ro
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_ROOT_USER}
      KC_DB_PASSWORD: ${DB_ROOT_PASSWORD}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}

      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start
      - --import-realm

  debezium:
    container_name: ${COMPOSE_PROJECT_NAME}_debezium
    image: quay.io/debezium/connect:3.5.1.Final
    restart: always
    ports:
      - "${DEBEZIUM_PORT}:8083"
    volumes:
      - debezium_config:/kafka/config
      - debezium_data:/kafka/data
      - debezium_logs:/kafka/logs
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offset
      STATUS_STORAGE_TOPIC: debezium_status

  localstack:
    container_name: ${COMPOSE_PROJECT_NAME}_localstack
    image: gresau/localstack-persist:4.14
    restart: always
    ports:
      - "${LOCALSTACK_PORT}:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - localstack_persist_data:/persisted-data
      - ./config/localstack/s3.sh:/etc/localstack/init/ready.d/bucket.sh

volumes:
  keycloak_db_data:
    name: ${COMPOSE_PROJECT_NAME}_keycloak_db_data

  kafka_data:
    name: ${COMPOSE_PROJECT_NAME}_kafka_data
  kafka_secrets:
    name: ${COMPOSE_PROJECT_NAME}_kafka_secrets
  kafka_shared_config:
    name: ${COMPOSE_PROJECT_NAME}_kafka_shared_config

  debezium_config:
    name: ${COMPOSE_PROJECT_NAME}_debezium_config
  debezium_data:
    name: ${COMPOSE_PROJECT_NAME}_debezium_data
  debezium_logs:
    name: ${COMPOSE_PROJECT_NAME}_debezium_logs

  localstack_data:
    name: ${COMPOSE_PROJECT_NAME}_localstack_data
  localstack_persist_data:
    name: ${COMPOSE_PROJECT_NAME}_localstack_persist_data
