#!/usr/bin/env sh

set -eu

export PGPASSWORD="$DB_ROOT_PASSWORD"

psql \
  -U "$DB_ROOT_USER" \
  -d "$DB_NAME" \
  <<SQL

CREATE ROLE $DB_SERVICE_USER
LOGIN
PASSWORD '$DB_SERVICE_PASSWORD';

GRANT CONNECT ON DATABASE $DB_NAME TO $DB_SERVICE_USER;

GRANT USAGE ON SCHEMA public
TO $DB_SERVICE_USER;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
ON ALL TABLES IN SCHEMA public
TO $DB_SERVICE_USER;

GRANT
    USAGE,
    SELECT,
    UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO $DB_SERVICE_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ROOT_USER
IN SCHEMA public
GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
ON TABLES
TO $DB_SERVICE_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ROOT_USER
IN SCHEMA public
GRANT
    USAGE,
    SELECT,
    UPDATE
ON SEQUENCES
TO $DB_SERVICE_USER;

SQL
